### ISSUE TITLE
Window closes instantly when running. 

### ISSUE THREAD

**Issue by EeziPZ** [kdik/godot-text-to-speech#1] opened 2022-11-05 21:52 UTC
Edit: Tested in 3.2 and is working. Must be some conflict with 3.5. 

Game window instantly closes when trying to run `yield($TextToSpeech2D.say(text, TextToSpeech.VOICE_AWB, speed), "completed")` 

No errors or debugging output. 

Godot version 3.5.1
Windows 10

Created a new project and installed the plugin. Same issue happens with the example scene.

**Comment by kdik** [comment] 2022-11-07 16:26
Hi, I was able to reproduce the issue.

3.4.5 works as well, the issues seem to begin starting with 3.5.0 and only on Windows, Linux works fine.

Until I find out the root cause of this a temporary workaround would be to stick with 3.4.5.

**Comment by Shando** [comment] 2023-02-11 21:29
Hi, is there any ETA for getting this working on 3.5?

**Comment by teddybear082** [comment] 2023-03-25 09:42
Hi do you think the reason with godot 3.5.1 could be because there is not a win64 lib just win 32?

Or actually maybe the issue is this? (mentions something breaking for gdnative in enums?) https://github.com/godot-rust/gdnative/pull/1011

**Comment by kdik** [comment] 2023-03-25 13:10
Even though the folder is named win32, the plugin is already 64bit.

I did some debugging. I debugged a bit and the issue seems to be on line 97 in tts.c, but my findings weren't conclusive and I haven't found a fix
https://github.com/kdik/godot-text-to-speech/blob/cc9f88841b5749a00b9afdc73d70f3513d3e94ca/src/tts.c#L97

**Comment by teddybear082** [comment] 2023-03-25 13:41
Ok thanks for letting me know and the quick response!!

**Comment by kdik** [comment] 2023-11-19 12:34
This issue has been fixed with, the fix is included in version 1.1

**Closed as completed by kdik** 2023-11-19 12:34 UTC
Labels: bug
